server:
  port: 8085  # API Gateway's port (use 8085 in production)

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prod_db  # Replace with your actual DB details
    username: prod_user
    password: prod_password
  cloud:
    config:
      uri: http://localhost:8086  # Config Server URL
  eureka:
    instance:
      prefer-ip-address: true
      hostname: localhost
    client:
      fetch-registry: true
      register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka  # Eureka server URL

